### ISSUE TITLE
Combine averages of multiple same revision-runs into one data point for win8

### ISSUE THREAD

**Issue by tschneidereit** [mozilla/arewefastyet#24] opened 2014-07-17 14:36 UTC
And perhaps other platforms, too. Octane is pretty noisy on all machines.

**Comment by nbp** [comment] 2015-02-02 13:17
Also, It would be nice to extract some confidence margin from these.  This would be a good first step into auto-reporting regressions.

Due to the last git-mirror issue, the FxOS slaves are unable to fetch newer version, but I am trying to let them run, as these highlight the noise level of the devices.

**Comment by h4writer** [comment] 2015-02-02 13:25
> This would be a good first step into auto-reporting regressions.

Not agreeing here. This would be a quite last step into auto-reporting regressions! First steps would be to detect possible regressions and let a peer classify them, before starting to worry about creating classifiers. Also note that most slaves don't have multiple scores for one revision.

Now combining averages of multiple same revisions would mostly be an aesthetic improvement. Because it would hide noise and make finding the actual regression visually easier on those machines.

**Comment by bnjbvr** [comment] 2018-09-10 10:06
Closing, we're not maintaining this version of AWFY anymore. See https://github.com/mozilla-frontend-infra/js-perf-dashboard for the new frontend.

**Closed by bnjbvr** 2018-09-10 10:06 UTC
Labels: enhancement
